general {
  lock_cmd = pidof hyprlock || hyprlock
}

# Dim the screen
listener {
  timeout = 120
  on-timeout = brightnessctl -d intel_backlight -s && brightnessctl -d intel_backlight set 15% && brightnessctl -d card1-eDP-2-backlight -s && brightnessctl -d card1-eDP-2-backlight set 15%
  on-resume = brightnessctl -d intel_backlight -r && brightnessctl -d card1-eDP-2-backlight -r
}

# Lock the screen
listener {
  timeout = 180 
  on-timeout = loginctl lock-session
}

# Turn the screen off
listener { 
#  on-timeout = 65
 # on-timeout = hyprctl dispatch dpms off
  #on-resume = hyprctl dispatch dpms on && brightnessctl -d intel_backlight  -r
}
